# Generated by Django 4.0.4 on 2022-06-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(default=4, max_length=128),
        ),
    ]
