# Generated by Django 4.0.5 on 2022-06-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_answer_is_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='image',
            field=models.ImageField(default=2, upload_to='quiz'),
            preserve_default=False,
        ),
    ]
